dist: trusty
sudo: required
language: c
before_install:
  - sudo apt-get install -y libpapi-dev python3-flake8 python3-pip valgrind
  - sudo pip3 install -r requirements.txt
script:
  # test code formatting
  - flake8 ./tools
  - flake8 ./configs --max-line-length=200 --ignore=F821

  # execute clang-O0 benchmark for all harnesses starting with 'a'
  - echo "CLANG=clang" > configs/env
  - echo "GCC=gcc" >> configs/env
  - echo "ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-3.4/bin/llvm-symbolizer" >> configs/env
  - echo "ASAN_OPTIONS=symbolize=1" >> configs/env
  - ./tools/bench.py -y my_results.json --filter-runtime=$FILTER_RUNTIME --exec-args="--warmup=0 --iterations=1" -j=4
matrix:
  include:
  - env: FILTER_RUNTIME='bugfinder-asan-gcc-O2'
  - env: FILTER_RUNTIME='bugfinder-asan-clang-O2'
  - env: FILTER_RUNTIME='bugfinder-msan-clang-O3'
  - env: FILTER_RUNTIME='bugfinder-ubsan-clang-O3'
  - env: FILTER_RUNTIME='bugfinder-tsan-clang-O3'
  - env: FILTER_RUNTIME='valgrind-O3'
  allow_failures:
  - env: FILTER_RUNTIME='bugfinder-msan-clang-O3'
  - env: FILTER_RUNTIME='bugfinder-ubsan-clang-O3'
  - env: FILTER_RUNTIME='bugfinder-tsan-clang-O3'
  - env: FILTER_RUNTIME='valgrind-O3'
after_failure:
  - ls --color ./benchmarks
