language: c
before_install:
  - sudo apt-get install -y libpapi-dev python-flake8
script:
  # test code formatting
  - flake8 ./tools

  # execute clang-O0 benchmark
  - echo "CLANG=clang" > configs/env
  - ./tools/bench.py -y my_results.json --filter-runtime=clang-O0
