language: c
before_install:
  - sudo apt-get install -y libpapi-dev python3-flake8 python3-pip
  - sudo pip3 install -r requirements.txt
script:
  # test code formatting
  - flake8 ./tools
  - flake8 ./configs --max-line-length=200 --ignore=F821

  # execute clang-O0 benchmark for all harnesses starting with 'a'
  - echo "CLANG=clang" > configs/env
  - ./tools/bench.py -y my_results.json --filter-runtime=asan-O3 --exec-args="--warmup=0 --iterations=1"
